# Generated by Django 5.2.3 on 2025-07-09 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id_convenio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_convenio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_empleado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_lic_vac',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id_feriado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pers_juridica',
            fields=[
                ('id_pers_juridica', models.AutoField(primary_key=True, serialize=False)),
                ('pers_juridica', models.CharField(max_length=50, unique=True)),
                ('domicilio', models.CharField(max_length=120)),
                ('cond_iva', models.CharField(max_length=45)),
                ('cuit', models.CharField(max_length=15)),
                ('cond_iibb', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_puesto', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_licencia',
            fields=[
                ('id_licencia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('dias', models.IntegerField()),
                ('pago', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Log_auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('nombre_tabla', models.CharField(max_length=100)),
                ('idregistro', models.IntegerField()),
                ('accion', models.CharField(max_length=40)),
                ('cambio', models.JSONField()),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.OneToOneField(db_column='Idempleado', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_e', models.DateField(auto_now_add=True)),
                ('nombres', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('fecha_nac', models.DateField()),
                ('num_hijos', models.IntegerField(default=0)),
                ('dr_personal', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=20)),
                ('cuil', models.CharField(max_length=15, unique=True)),
                ('id_civil', models.ForeignKey(db_column='id_civil', on_delete=django.db.models.deletion.PROTECT, to='nucleo.estadocivil')),
                ('id_localidad', models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.PROTECT, to='nucleo.localidad')),
                ('id_nacionalidad', models.ForeignKey(db_column='id_nacionalidad', on_delete=django.db.models.deletion.PROTECT, to='nucleo.nacionalidad')),
                ('id_sexo', models.ForeignKey(db_column='id_sexo', on_delete=django.db.models.deletion.PROTECT, to='nucleo.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField(default=False)),
                ('martes', models.BooleanField(default=False)),
                ('miercoles', models.BooleanField(default=False)),
                ('jueves', models.BooleanField(default=False)),
                ('viernes', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('idempleado', models.ForeignKey(db_column='idempleado', on_delete=django.db.models.deletion.CASCADE, to='nucleo.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(db_column='provincia_id', on_delete=django.db.models.deletion.PROTECT, to='nucleo.provincia'),
        ),
        migrations.CreateModel(
            name='Empleado_el',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_el', models.DateField(auto_now_add=True)),
                ('alta_ant', models.DateField()),
                ('id_convenio', models.ForeignKey(db_column='id_convenio', on_delete=django.db.models.deletion.PROTECT, to='nucleo.convenio')),
                ('idempleado', models.ForeignKey(db_column='idempleado', on_delete=django.db.models.deletion.CASCADE, to='nucleo.empleado')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='nucleo.estado_empleado')),
                ('id_puesto', models.ForeignKey(db_column='id_puesto', on_delete=django.db.models.deletion.PROTECT, to='nucleo.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_vacaciones',
            fields=[
                ('idsolicitudvac', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sol_vac', models.DateField(auto_now_add=True)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('comentario', models.CharField(max_length=200)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='nucleo.estado_lic_vac')),
                ('idempleado', models.ForeignKey(db_column='idempleado', on_delete=django.db.models.deletion.PROTECT, to='nucleo.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('sucursal', models.CharField(max_length=30)),
                ('suc_dire', models.CharField(max_length=120)),
                ('suc_mail', models.CharField(max_length=50)),
                ('id_pers_juridica', models.ForeignKey(db_column='id_pers_juridica', on_delete=django.db.models.deletion.PROTECT, to='nucleo.pers_juridica')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_licencia',
            fields=[
                ('idsolicitudlic', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sqllc', models.DateField(auto_now_add=True)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('texto_gestor', models.CharField(blank=True, max_length=200, null=True)),
                ('archivo', models.CharField(blank=True, max_length=200, null=True)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='nucleo.estado_lic_vac')),
                ('idempleado', models.ForeignKey(db_column='idempleado', on_delete=django.db.models.deletion.PROTECT, to='nucleo.empleado')),
                ('id_licencia', models.ForeignKey(db_column='id_licencia', on_delete=django.db.models.deletion.PROTECT, to='nucleo.tipo_licencia')),
            ],
        ),
        migrations.CreateModel(
            name='Vacaciones_otorgadas',
            fields=[
                ('id_vacaciones', models.AutoField(primary_key=True, serialize=False)),
                ('inicio_consumo', models.DateField()),
                ('fin_consumo', models.DateField()),
                ('dias_disponibles', models.IntegerField()),
                ('dias_consumidos', models.IntegerField()),
                ('idempleado', models.ForeignKey(db_column='idempleado', on_delete=django.db.models.deletion.PROTECT, to='nucleo.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado_eo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_eo', models.DateField(auto_now_add=True)),
                ('idempleado', models.ForeignKey(db_column='idempleado', on_delete=django.db.models.deletion.CASCADE, to='nucleo.empleado')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='nucleo.sucursal')),
            ],
            options={
                'unique_together': {('fecha_eo', 'idempleado')},
            },
        ),
    ]
