# Generated by Django 5.2.4 on 2025-08-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_empleado_el_fecha_est'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_laboral',
            fields=[
                ('id_estado_laboral', models.AutoField(primary_key=True, serialize=False)),
                ('estado_laboral', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
