# Generated by Django 5.2.4 on 2025-08-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_estado_laboral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado_laboral',
            old_name='estado_laboral',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='estado_laboral',
            old_name='id_estado_laboral',
            new_name='id_estado',
        ),
        migrations.RemoveField(
            model_name='estado_laboral',
            name='descripcion',
        ),
    ]
