# Generated by Django 5.2.3 on 2025-08-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_rename_estado_laboral_estado_laboral_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_licencia',
            name='dias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
