# Generated by Django 5.2.3 on 2025-10-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_alter_tipo_licencia_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
