"""
Django settings for gestion_rrhh project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import mimetypes
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name):
    value = os.environ.get(name, '')
    if not value:
        return []
    normalized = value.replace(';', ',')
    return [item.strip() for item in normalized.split(',') if item.strip()]


def host_from_url(raw_value):
    if not raw_value:
        return ''
    candidate = raw_value.strip()
    if '://' not in candidate:
        candidate = f'https://{candidate}'
    return urlparse(candidate).hostname or ''


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-vt=usd67mi35!hx4e!5f0zm5)_=ig07-m-3ig(t0%7h7xht3bl')

# SECURITY WARNING: don't run with debug turned on in production!
DJANGO_ENV = os.environ.get('DJANGO_ENV', 'development').lower()
DEBUG = env_bool('DJANGO_DEBUG', DJANGO_ENV != 'production')

default_allowed_hosts = [
    'localhost',
    '127.0.0.1',
    'testserver',
    '.sslip.io',
]
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS') or env_list('ALLOWED_HOSTS') or default_allowed_hosts

coolify_host = host_from_url(os.environ.get('COOLIFY_FQDN', ''))
if coolify_host and coolify_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(coolify_host)

site_url_env = os.environ.get('SITE_URL', '')
site_host = host_from_url(site_url_env)
if site_host and site_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(site_host)

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS') or env_list('CSRF_TRUSTED_ORIGINS')
if not CSRF_TRUSTED_ORIGINS:
    csrf_origins = []
    for host in ALLOWED_HOSTS:
        if host in {'*', 'localhost', '127.0.0.1', 'testserver'}:
            continue
        clean_host = host.lstrip('.')
        if not clean_host:
            continue
        csrf_origins.append(f'https://{clean_host}')
        if host.startswith('.'):
            csrf_origins.append(f'https://*.{clean_host}')
    CSRF_TRUSTED_ORIGINS = sorted(set(csrf_origins))

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', False)

SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', SECURE_SSL_REDIRECT)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', SECURE_SSL_REDIRECT)

STATIC_URL = '/static/'

if DEBUG:
    STATICFILES_DIRS = [BASE_DIR / 'nucleo' / 'static']
else:
    STATIC_ROOT = Path('/srv/static')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# URL base del sitio para emails
SITE_URL = site_url_env or (f'https://{coolify_host}' if coolify_host else 'http://localhost:8000')




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nucleo',  # <-- tu app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_rrhh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'nucleo.context_processors.empleado_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_rrhh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME', 'GRHP'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'C05m05'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'

# Configuración de sesiones más segura
SESSION_COOKIE_AGE = 86400  # 24 horas en segundos
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # La sesión expira al cerrar el navegador
SESSION_SAVE_EVERY_REQUEST = True  # Actualiza la expiración en cada request
SESSION_COOKIE_HTTPONLY = True  # Prevenir acceso por JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'  # Protección CSRF básica

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'farmaciagomezdegalarze@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'qtud hldf rcoi itro')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

MEDIA_URL = '/media/'
MEDIA_ROOT = Path('/srv/gestion_rrhh_media')

mimetypes.add_type("application/pdf", ".pdf", True)
